CREATE TABLE tests (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    test_title VARCHAR(255) NOT NULL,
    test_code VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    duration INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
